packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'core-js': true
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - autoprefixer@10.5.3
  - pinia@4.0.2
  - prettier-plugin-tailwindcss@0.8.1
  - proto-tailwindcss-clrs@0.0.516
