packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'core-js': true
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - '@vitejs/plugin-vue@6.0.10'
  - prettier@3.9.10
  - proto-tailwindcss-clrs@0.0.562
