packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'core-js': true
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - autoprefixer@10.5.1
  - proto-tailwindcss-clrs@0.0.509
